easy_admin:
   site_name: 'Product Service'
   entities:
       # List the entity class name you want to manage
       - App\Entity\Product
       - App\Entity\Offer
       - App\Entity\Orders
       - App\Entity\OrderItem
       - App\Entity\Customer
