# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
   view:
       view_response_listener:  true
   exception:
       exception_controller: 'fos_rest.exception.controller:showAction'
       codes:
           Doctrine\ORM\EntityNotFoundException: 404
   format_listener:
       rules:
           - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
           - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
